# Generated by Django 3.2 on 2023-04-29 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230429_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitlesGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ManyToManyField(to='reviews.Genres')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_id', to='reviews.titles', verbose_name='id произведения')),
            ],
        ),
    ]
