# Generated by Django 3.2 on 2023-04-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_titlesgenres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(to='reviews.Genres'),
        ),
        migrations.DeleteModel(
            name='TitlesGenres',
        ),
    ]
