# Generated by Django 3.2 on 2023-04-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_review_comments_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='reviews',
            new_name='review',
        ),
    ]
