# Generated by Django 3.2 on 2023-04-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_reviews_comments_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
