# Generated by Django 3.2 on 2023-04-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rename_reviews_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
