# Generated by Django 3.2 on 2023-04-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230429_1123'),
        ('reviews', '0007_alter_user_id'),
    ]

    operations = [
    ]
