# Generated by Django 3.2 on 2023-04-30 05:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_rename_review_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug категории'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата публикации комментария', verbose_name='Дата публикации комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.reviews', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(help_text='Ваш комментарий', verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug жанра'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Здесь нужно выбрать категорию.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, default=1, help_text='Введите описание.', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Нужно выбрать жанр.', related_name='titles', to='reviews.Genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(default=2023, help_text='Введите год выпуска.', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=1, max_length=1024, verbose_name='Биография'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=20),
        ),
    ]
